service: minutes-serverless

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  stage: prod
  region: ap-northeast-1
  profile: minutes
  endpointType: regional

package:
  exclude:
    - layer.zip
    - YcPwmCj0iGI.m4a
    - YcPwmCj0iGI.m4a.txt

functions:
  audioMaker:
    handler: audioMaker.main
    events:
      - httpApi:
          path: /transcribe/{video_id}
          method: get
  transcriber:
    handler: transcriber.main
